version: "3.4"
services:
  app:
    container_name: submission
    image: submission
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 4041:3000
